all:	atslogd atslogmaster

atslogd:
	@txt2man -s 8 -t "atslogd" en/atslogd.8.txt > en/atslogd.8
	@txt2man -s 8 -t "atslogd" ru.KOI8-R/atslogd.8.txt > ru.KOI8-R/atslogd.8
atslogmaster:
	@txt2man -s 8 -t "atslogmaster" en/atslogmaster.8.txt > en/atslogmaster.8
	@txt2man -s 8 -t "atslogmaster" ru.KOI8-R/atslogmaster.8.txt > ru.KOI8-R/atslogmaster.8