#!/bin/sh
# ATSlog version @version@ build @buildnumber@ www.atslog.dp.ua  
# Copyright (C) 2003 Denis CyxoB www.yamiyam.dp.ua
#

# Установим рабочие переменные
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:.:$bindir:$sharedir
UNAME=`uname`
for i
do
    case "$1" in
	"--help")
	    HELP="yes"
	;;
	--sqlroot=*)
	    sqlrootpassword=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
	--deinstall)
	    TODO="deinstall"
	                  
	;;
	--install)
	    TODO="install"
	;;
	--prefix=*)
	    PREFIX=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    esac
    shift
done

if [ -z "$PREFIX" ]
then
    PREFIX="/usr/local"
fi

if [ -z "$TODO" ]
then
    HELP="yes"
fi

echo "Usage: installing [options]
Options: [defaults in brackets after descriptions]
Use: installing --help for help."

if [ "$HELP" = "yes" ];then

echo "
--sqlroot=PASSWORD Пароль пользователя root SQL сервера (не системного
                   пользователя root). Этот пароль  нужен только для
		   инсталляции или обновления ATSlog. В дальнейшей работе
		   не используется.

--deinstall        Удаление ATSlog.

--install          Установка ATSlog.

--prefix=PREFIX    install architecture-independent files in PREFIX
                    [/usr/local]
"
    exit 0
fi

readpasswd(){
    echo "ожидается ввод"
    echo "Введите пароль для пользователя root SQL сервера (не для системного"
    echo "пользователя root). Этот пароль  нужен только для инсталляции или"
    echo "обновления ATSlog. В дальнейшей работе не используется."
    trap 'exit;' 0 1 2 3 15
    echo -n "Пароль: "
    stty -echo
    read sqlrootpassword
    stty echo
    echo ""
}
copying(){

    if [ ! -d $logdir ];then
        mkdir -p $logdir
	chmod 700 $logdir
	chown root:wheel $logdir
    else
        chmod 700 $logdir
    fi
    if [ ! -d $libdir ];then
        mkdir -p $libdir
	chmod 755 $libdir
	chown root:wheel $libdir
    fi
    if [ ! -d $bindir ];then
        mkdir -p $bindir
	chmod 755 $bindir
	chown root:wheel $bindir
    fi
    if [ ! -d $sharedir ];then
        mkdir -p $sharedir
	chmod 755 $sharedir
	chown root:wheel $sharedir
    fi
    if [ ! -d $sharedir/$langdir ];then
        mkdir -p $sharedir/$langdir
	chmod 755 $sharedir/$langdir
	chown root:wheel $sharedir/$langdir
    fi
    if [ ! -d $PREFIX/www/atslog ];then
        mkdir -p $PREFIX/www/atslog
	chmod 555 $PREFIX/www/atslog
    fi
    touch $logdir/$callslogfile
    touch $logdir/$startlogfile
    touch $logdir/$curcallslogfile
    touch $logdir/$notwritelog

    DAILYPATH=`dirname $monthlyscript`
    MONTHLYPATH=`dirname $dailyscript`

    for PERPATH in $DAILYPATH $MONTHLYPATH
    do
	if [ ! -d $PERPATH ];then
    	    mkdir -p $PERPATH
    	    chmod 555 $PERPATH
	fi
    done
    

    if [ "$UNAME" = "Linux" ];then
	INITDIR=/etc/rc.d
	for stasto in "rc2.d/K01atslogd" "rc2.d/S80atslogd" "rc3.d/K01atslogd" "rc3.d/S80atslogd" "rc5.d/K01atslogd" "rc5.d/S80atslogd"
	do
	    if [ ! -L $INITDIR/$stasto ];then
		ln -s $initscript $INITDIR/$stasto
	    fi
	done

	if [ ! -L /etc/atslog.conf ];then
	    ln -s $PREFIX/etc/atslog.conf /etc/atslog.conf
	fi
    fi
    install -m 755 ./atslogdinit $initscript
    install -m 755 ./include/atslogrotate $monthlyscript
    install -m 755 ./include/atslogdaily $dailyscript
    install -m 755 ./include/atslogdb.pl.tmp $bindir/$atslogdb
    install -m 600 ./atslog.conf $PREFIX/etc/atslog.conf
    install -m 644 ./atslog.conf $PREFIX/etc/atslog.conf.default
    install -m 644 ./atslog.conf $sharedir/atslog.conf.default
    install -m 644 ./libexec/kx-ta616-308-ru.lib $libdir/kx-ta616-308-ru.lib
    install -m 644 ./libexec/gd-320.lib $libdir/gd-320.lib
    install -m 644 ./libexec/skp-816.lib $libdir/skp-816.lib
    install -m 644 ./libexec/nx-820.lib $libdir/nx-820.lib
    install -m 644 ./libexec/kx-td1232.lib $libdir/kx-td1232.lib
    install -m 644 ./libexec/kx-td816ru.lib $libdir/kx-td816ru.lib
    install -m 755 ./src/atslogd/atslogd $bindir/$atslogd
    install -m 755 ./include/atslogmaster $bindir/$masterscript
    install -m 755 ./include/atslogcleardb.pl.tmp $bindir/$cleardb
    install -m 644 ./sql/createsqltables.sql.default $sharedir/createsqltables.sql.default
    install -m 644 ./installing $sharedir/installing
    install -m 644 ./INSTALL $sharedir/INSTALL
    install -m 644 ./Makefile $sharedir/Makefile
    install -m 644 ./README $sharedir/README
    install -m 644 ./DEINSTALL $sharedir/DEINSTALL
    install -m 644 ./UPDATING $sharedir/UPDATING
    install -m 644 ./USING $sharedir/USING
    install -m 644 ./CHANGES $sharedir/CHANGES
    cp -R textlogs $sharedir
    cp -R www/* $PREFIX/www
    cp -R conf.inc $PREFIX/www/atslog/include/set
    chmod -R a-w,a+rX $PREFIX/www/atslog
    cp -R lang/* $sharedir/$langdir
}

case "$TODO" in
deinstall)

# Start deinstalling
    if [ -r $PREFIX/etc/atslog.conf ];then
	. $PREFIX/etc/atslog.conf
    elif [ -r ./include/atslog.conf.default ]; then
    	. ./include/atslog.conf.default
    elif [ -r ./atslog.conf.default ]; then
    	. ./atslog.conf.default
    else
        echo "Can't open config file."
        exit 1
    fi

    rm $initscript
    if [ "$UNAME" = "Linux" ];then
	INITDIR=/etc/rc.d
	for stasto in "rc2.d/K01atslogd" "rc2.d/S80atslogd" "rc3.d/K01atslogd" "rc3.d/S80atslogd" "rc5.d/K01atslogd" "rc5.d/S80atslogd"
	do
	    if [ -L $INITDIR/$stasto ];then
		rm  $INITDIR/$stasto
	    fi
	done
    fi
    rm $monthlyscript
    rm $dailyscript
    rm $bindir/$atslogdb
    rm /usr/local/etc/atslog.conf.default
    rm $sharedir/atslog.conf.default
    rm $libdir/kx-ta616-308-ru.lib
    rm $libdir/gd-320.lib
    rm $libdir/skp-816.lib
    rm $libdir/nx-820.lib
    rm $libdir/kx-td1232.lib
    rm $libdir/kx-td816ru.lib
    rm $bindir/$masterscript
    rm $bindir/$atslogd
    rm $bindir/$cleardb
    rm $sharedir/installing
    rm $sharedir/INSTALL
    rm $sharedir/Makefile
    rm $sharedir/DEINSTALL
    rm $sharedir/README
    rm $sharedir/UPDATING
    rm $sharedir/USING
    rm $sharedir/CHANGES
    rm $sharedir/createsqltables.sql.default

    rm -rf $sharedir/$langdir
    rm -rf $PREFIX/www/atslog
    rm -rf $sharedir/textlogs

    if [ ! -s $logdir/$callslogfile ];then
	rm -f $logdir/$callslogfile
    fi
    if [ ! -s $logdir/$curcallslogfile ];then
	rm -f $logdir/$curcallslogfile
    fi
    if [ ! -s $logdir/$startlogfile ];then
	rm -f $logdir/$startlogfile
    fi
    if [ ! -s $logdir/$notwritelog ];then
	rm -f $logdir/$notwritelog
    fi

    DAILYPATH=`dirname $monthlyscript`
    MONTHLYPATH=`dirname $dailyscript`
    #echo $DAILYPATH $MONTHLYPATH

    for PERPATH in $DAILYPATH $MONTHLYPATH $sharedir $libdir $logdir
    do
	if [ -d $PERPATH ];then
	    if [ `ls -1l $PERPATH | grep -c -` = 0 ];then
		rmdir -p $PERPATH 2> /dev/null
	    else
		echo "Директория $PERPATH содержит файлы и не может быть удалена!"
	    fi
	fi
    done

    echo "Удаление завершено. Не забудьте очистить базы SQL сервера"
    ;;
install)

# Readin config file
    if [ -r ./atslog.conf ]; then
	. ./atslog.conf
    else
        echo "Can't open config file. Please start configure."
        exit 1
    fi
# Start updating
    if [ -f ./updatesqltables.sql ];then
        echo -n "Обновляем базы данных SQL сервера: "
	mysql -f -h $sqlhost < ./updatesqltables.sql 1>/dev/null 2>./install.log
	if [ "$?" -eq 0 ]
	then
	    echo "OK"
	else
	    mysql -h $sqlhost -u $sqlmasteruser --password=$sqlmaspasswd < ./updatesqltables.sql 1>/dev/null 2>>./install.log
	    if [ "$?" -eq 0 ]
	    then
		echo "OK"
	    else
		if [ -z "$sqlrootpassword" ]
		then
		    # Call to function
		    readpasswd
		else
		    echo "ожидается продолжение"
		fi
		echo -n "Продолжаем обновление: "
		mysql -f -h $sqlhost --password=$sqlrootpassword < ./updatesqltables.sql 1>/dev/null 2>>./install.log
		if [ "$?" -eq 0 ]
		then
		    echo "OK"
		else
		    echo "ОШИБКА"
		    ERROECHO=1
		fi

	    fi
	fi
    fi
# Start new installation
    if [ -f ./createsqltables.sql ];then
        echo -n "Создаём базы данных и таблицы SQL сервера: "
	mysql -f -h $sqlhost < ./createsqltables.sql 1>/dev/null 2>./install.log
	if [ "$?" -eq 0 ]
	then
	    echo "OK"
	else
	    if [ -z "$sqlrootpassword" ]
	    then
		# Call to function
		readpasswd
	    else
		echo "ожидается продолжение"
	    fi
	    echo -n "Продолжаем создание: "
	    mysql -f -h $sqlhost --password=$sqlrootpassword < ./createsqltables.sql 1>/dev/null 2>>./install.log
	    if [ "$?" -eq 0 ]
	    then
		echo "OK"
	    else
		echo "ОШИБКА"
		ERROECHO=1
	    fi
	fi
    fi

    echo "Копирование файлов"
# Call to function
    copying

    if [ "$ERROECHO" != "1" ]
    then
	echo "Установка завершена успешно. Конфигурационный файл $PREFIX/etc/atslog.conf"
    else
	echo "Установка завершена с ошибками. Подробнее смотрите install.log"
	echo "В результате некоторые действия не были выполнены."
	echo "Конфигурационный файл $PREFIX/etc/atslog.conf"
    fi
    ;;
esac

exit $?
