#!/bin/sh
# ATSlog version @version@ build @buildnumber@ www.atslog.dp.ua  
# Copyright (C) 2003 Denis CyxoB www.yamiyam.dp.ua
#

# Установим рабочие переменные
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:.:$bindir:$sharedir
UNAME=`uname`
for i
do
    case "$1" in
	"--help")
	    HELP="yes"
	;;
	--sqlroot=*)
	    sqlrootpassword=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
	--deinstall)
	    TODO="deinstall"
	                  
	;;
	--install)
	    TODO="install"
	;;
	--prefix=*)
	    PREFIX=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    esac
    shift
done

if [ -z "$PREFIX" ]
then
    PREFIX="/usr/local"
fi

if [ -z "$TODO" ]
then
    HELP="yes"
fi

echo "Usage: installing [options]
Options: [defaults in brackets after descriptions]
Use: installing --help for help."

if [ "$HELP" = "yes" ];then

echo "
--sqlroot=PASSWORD Пароль пользователя root SQL сервера (не системного
                   пользователя root). Этот пароль  нужен только для
		   инсталляции или обновления ATSlog. В дальнейшей работе
		   не используется.

--deinstall        Удаление ATSlog.

--install          Установка ATSlog.

--prefix=PREFIX    install architecture-independent files in PREFIX
                    [/usr/local]
"
    exit 0
fi

readpasswd(){
    echo "Введите пароль для суперпользователя SQL сервера (не для системного"
    echo "суперпользователя). Этот пароль  нужен только для установки или"
    echo "обновления ATSlog. В дальнейшей работе он не будет использоваться."
    trap 'exit;' 0 1 2 3 15
    echo -n "Пароль: "
    stty -echo
    read sqlrootpassword
    stty echo
    echo "OK"
}
copying(){

    if [ ! -d $logdir ];then
        mkdir -p $logdir
	chmod 700 $logdir
	chown root:wheel $logdir
    else
        chmod 700 $logdir
    fi
    if [ ! -d $libdir ];then
        mkdir -p $libdir
	chmod 755 $libdir
	chown root:wheel $libdir
    fi
    if [ ! -d $bindir ];then
        mkdir -p $bindir
	chmod 755 $bindir
	chown root:wheel $bindir
    fi
    if [ ! -d $sharedir ];then
        mkdir -p $sharedir
	chmod 755 $sharedir
	chown root:wheel $sharedir
    fi
    if [ ! -d $sharedir/$langdir ];then
        mkdir -p $sharedir/$langdir
	chmod 755 $sharedir/$langdir
	chown root:wheel $sharedir/$langdir
    fi
    if [ ! -d $PREFIX/www/atslog ];then
        mkdir -p $PREFIX/www/atslog
	chmod 555 $PREFIX/www/atslog
    fi
    if [ ! -d $sharedir/sql ];then
        mkdir -p $sharedir/sql
	chmod 555 $sharedir/sql
    fi
    if [ ! -d $PREFIX/etc ];then
        mkdir -p $PREFIX/etc
    fi

    touch $logdir/$callslogfile
    touch $logdir/$startlogfile
    touch $logdir/$curcallslogfile
    touch $logdir/$notwritelog

    DAILYPATH=`dirname $monthlyscript`
    MONTHLYPATH=`dirname $dailyscript`
    PIDFILEPATH=`dirname $pidfile`

    for PERPATH in $DAILYPATH $MONTHLYPATH $PIDFILEPATH
    do
	if [ ! -d $PERPATH ];then
    	    mkdir -p $PERPATH
    	    chmod 555 $PERPATH
	fi
    done
    

    if [ "$UNAME" = "Linux" ];then
	INITDIR=/etc/rc.d
	for stasto in "rc2.d/K01atslogd" "rc2.d/S80atslogd" "rc3.d/K01atslogd" "rc3.d/S80atslogd" "rc5.d/K01atslogd" "rc5.d/S80atslogd"
	do
	    if [ ! -L $INITDIR/$stasto ];then
		ln -s $initscript $INITDIR/$stasto
	    fi
	done

	if [ ! -L /etc/atslog.conf ];then
	    ln -s $PREFIX/etc/atslog.conf /etc/atslog.conf
	fi
    fi
    if [ "$UNAME" = "FreeBSD" ];then
	if [ ! -d $PREFIX/etc/rc.d ];then
	    mkdir -p $PREFIX/etc/rc.d
	fi                          
    fi

    install -m 755 ./atslogdinit $initscript
    install -m 755 ./atslogrotate $monthlyscript
    install -m 755 ./atslogdaily $dailyscript
    install -m 755 ./atslogdb.pl $bindir/$atslogdb
    install -m 600 ./atslog.conf $PREFIX/etc/atslog.conf
    install -m 644 ./atslog.conf $PREFIX/etc/atslog.conf.default
    install -m 644 ./atslog.conf $sharedir/atslog.conf.default
    install -m 644 ./libexec/kx-ta616-308-ru.lib $libdir/kx-ta616-308-ru.lib
    install -m 644 ./libexec/gd-320.lib $libdir/gd-320.lib
    install -m 644 ./libexec/gdk-100.lib $libdir/gdk-100.lib
    install -m 644 ./libexec/ghx-46.lib $libdir/ghx-46.lib
    install -m 644 ./libexec/skp-816.lib $libdir/skp-816.lib
    install -m 644 ./libexec/nx-820.lib $libdir/nx-820.lib
    install -m 644 ./libexec/hicom-350h.lib $libdir/hicom-350h.lib
    install -m 644 ./libexec/kx-td1232.lib $libdir/kx-td1232.lib
    install -m 644 ./libexec/kx-td816ru.lib $libdir/kx-td816ru.lib
    install -m 755 ./src/atslogd/atslogd $bindir/$atslogd
    install -m 755 ./atslogmaster $bindir/$masterscript
    install -m 755 ./atslogcleardb.pl $bindir/$cleardb
    install -m 644 ./installing.out $sharedir/installing
    install -m 644 ./INSTALL $sharedir/INSTALL
    install -m 644 ./Makefile.out $sharedir/Makefile
    install -m 644 ./README $sharedir/README
    install -m 644 ./DEINSTALL $sharedir/DEINSTALL
    install -m 644 ./UPDATING $sharedir/UPDATING
    install -m 644 ./USING $sharedir/USING
    install -m 644 ./CHANGES $sharedir/CHANGES
    cp -R textlogs $sharedir
    cp -R www/* $PREFIX/www
    cp -R sql/* $sharedir/sql
    cp -R conf.inc $PREFIX/www/atslog/include/set
    chmod -R a-w,a+rX $PREFIX/www/atslog
    cp -R lang/* $sharedir/$langdir
}

case "$TODO" in
deinstall)

# Start deinstalling
    if [ -r $PREFIX/etc/atslog.conf ];then
	. $PREFIX/etc/atslog.conf
    elif [ -r ./include/atslog.conf.default ]; then
    	. ./include/atslog.conf.default
    elif [ -r ./atslog.conf.default ]; then
    	. ./atslog.conf.default
    else
        echo "Can't open config file."
        exit 1
    fi

    rm $initscript
    if [ "$UNAME" = "Linux" ];then
	INITDIR=/etc/rc.d
	for stasto in "rc2.d/K01atslogd" "rc2.d/S80atslogd" "rc3.d/K01atslogd" "rc3.d/S80atslogd" "rc5.d/K01atslogd" "rc5.d/S80atslogd"
	do
	    if [ -L $INITDIR/$stasto ];then
		rm  $INITDIR/$stasto
	    fi
	done
    fi
    rm $monthlyscript
    rm $dailyscript
    rm $bindir/$atslogdb
    rm $PREFIX/etc/atslog.conf.default
    rm $sharedir/atslog.conf.default
    rm $libdir/kx-ta616-308-ru.lib
    rm $libdir/gd-320.lib
    rm $libdir/gdk-100.lib
    rm $libdir/ghx-46.lib
    rm $libdir/skp-816.lib
    rm $libdir/nx-820.lib
    rm $libdir/hicom-350h.lib
    rm $libdir/kx-td1232.lib
    rm $libdir/kx-td816ru.lib
    rm $bindir/$masterscript
    rm $bindir/$atslogd
    rm $bindir/$cleardb
    rm $sharedir/installing
    rm $sharedir/INSTALL
    rm $sharedir/Makefile
    rm $sharedir/DEINSTALL
    rm $sharedir/README
    rm $sharedir/UPDATING
    rm $sharedir/USING
    rm $sharedir/CHANGES

    rm -rf $sharedir/$langdir
    rm -rf $PREFIX/www/atslog
    rm -rf $sharedir/sql
    rm -rf $sharedir/textlogs

    if [ ! -s $logdir/$callslogfile ];then
	rm -f $logdir/$callslogfile
    fi
    if [ ! -s $logdir/$curcallslogfile ];then
	rm -f $logdir/$curcallslogfile
    fi
    if [ ! -s $logdir/$startlogfile ];then
	rm -f $logdir/$startlogfile
    fi
    if [ ! -s $logdir/$notwritelog ];then
	rm -f $logdir/$notwritelog
    fi

    DAILYPATH=`dirname $monthlyscript`
    MONTHLYPATH=`dirname $dailyscript`
    PIDFILEPATH=`dirname $pidfile`
    #echo $DAILYPATH $MONTHLYPATH

    for PERPATH in $DAILYPATH $MONTHLYPATH $PIDFILEPATH $sharedir $libdir $logdir
    do
	if [ -d $PERPATH ];then
	    if [ `ls -1l $PERPATH | grep -c -` = 0 ];then
		rmdir -p $PERPATH 2> /dev/null
	    else
		echo "Директория $PERPATH содержит файлы и не может быть удалена!"
	    fi
	fi
    done

    echo "Удаление завершено. Не забудьте очистить базы SQL сервера"
    ;;
install)

# Readin config file
    if [ -r ./atslog.conf ]; then
	. ./atslog.conf
    else
        echo "Can't open config file. Please start configure."
        exit 1
    fi

# Start SQL operations
    if [ -f updatesqltables.pgsql.sql -o -f createsqltables.pgsql.sql -o -f createuser.pgsql.sql ];then
	SQLTYPE=pgsql
	sqltype=PostgreSQL
    else
	SQLTYPE=mysql
	sqltype=MySQL
    fi

    for sqlinfo in createuser.$SQLTYPE.sql createsqltables.$SQLTYPE.sql updatesqltables.$SQLTYPE.sql
    do
	if [ -f ./$sqlinfo ];then
	    DBOPERATIONS=true
	fi
    done

    if [ $DBOPERATIONS ];then
    	echo -n "Проводятся операции с базами данных $sqltype сервера: "
    fi

    ERROECHO=0
    LASTOPERAT=0
    for sqlfile in createuser.$SQLTYPE.sql createsqltables.$SQLTYPE.sql updatesqltables.$SQLTYPE.sql
    do
    if [ -f ./$sqlfile ];then
        if [ "$sqlfile" = "createsqltables.pgsql.sql" ];then
    	    cat ./$sqlfile | ./scripts/createdb.out.pl $sqlmaspasswd $sqlmasteruser 2>>./install.log
	    if [ $? -ne 0 ];then
		ERROECHO=1
	    fi
	else
	    cat ./$sqlfile | ./scripts/createdb.out.pl 2>>./install.log
	    LASTOPERAT=$?
	    if [ $LASTOPERAT -eq 1 ];then
	        ERROECHO=1
	    fi
	    if [ $LASTOPERAT -eq 2 ];then
	        if [ -z "$sqlrootpassword" ]
	        then
		    echo "NEED A PASSWORD!"
		    # Call to function
	    	    readpasswd
		else
		    echo -n "Продолжение операций с базами данных: "
	    	fi
		cat ./$sqlfile | ./scripts/createdb.out.pl $sqlrootpassword 2>>./install.log
		if [ $? -ne 0 ];then
		    ERROECHO=1
		fi
	    fi
	fi
    fi
    done
    
    if [ $DBOPERATIONS ];then
	if [ $ERROECHO != 1 ];then
    	    echo "OK"
	else
    	    echo "ОШИБКА"
	fi
    fi

    echo "Копирование файлов"
# Call to function
    copying

    if [ "$ERROECHO" != "1" ]
    then
	echo "Установка завершена успешно. Конфигурационный файл $PREFIX/etc/atslog.conf"
    else
	echo "Установка завершена с ошибками. Подробнее смотрите install.log"
	echo "В результате некоторые действия не были выполнены."
	echo "Конфигурационный файл $PREFIX/etc/atslog.conf"
    fi
    ;;
esac

exit $?
