<?

 /*
 
   Параметры для web-интерфейса ATSlog
                                              
 */                                       
                                               
$sqlhost='';
$sqldatabase='';
$sqlmaspasswd='';
$sqlmasteruser='';
$sqltype=''; // PostgreSQL or MySQL
$model='';
$ADODB_CACHE_DIR = '/tmp/adodb';
$ADODB_CACHE_TTL = 60*60; // 1 час. Время жизни кеша SQL запросов.
$debugMode=FALSE; // Режим отладки.
$demoMode=FALSE; // Демонстрационный режим.

?>