all:	atslogd atslogmaster

atslogd:
	@export LANG=en_US;txt2man -s 8 -t "atslogd" ./atslogd.8.txt > ./atslogd.8
	@export LANG=en_US;txt2man -s 8 -t "atslogd" ./atslogd.8.txt > ./atslogd.8
atslogmaster:
	@export LANG=en_US;txt2man -s 8 -t "atslogmaster" ./atslogmaster.8.txt > ./atslogmaster.8
	@export LANG=en_US;txt2man -s 8 -t "atslogmaster" ./atslogmaster.8.txt > ./atslogmaster.8
