<?php                   

// Standart color scheme

$COLORS = array (
    SchemeName				=> 'Standart',
    BodyBgcolor                         => '',
    BodyText                            => '',
    BodyLink                            => '',
    BodyVlink                           => '',
    BodyAlink                           => '',
    StyleBodyScrollbarBaseColor         => '',
    StyleBodyScrollbarArrowColor        => '',
    StyleAHover                         => '',
    StyleAMenu                          => '',
    StyleAMenuHover                     => '',
    StyleInputBackground                => '',
    StyleSelectBackground               => '',
    StyleTextareaBackground             => '',
    StyleInputSubmitBackground          => '',
    StyleInputSubmitBorderRight         => '',
    StyleInputSubmitBorderTop           => '',
    StyleInputSubmitBorderLeft          => '',
    StyleInputSubmitBorderBottom        => '',
    FooterTableBgcolor			=> '',
    BaseTablesBgcolor                   => '',
    BaseTrBgcolor                       => '',
    BaseBorderTableBgcolor              => '',
    TrOnmouseOne                        => '',
    TrOnmouseTwo                        => '',
    TrOnmouseThree                      => '',
    AltogetherTrBgcolor                 => '',
    TotalTrBgcolor                      => '',
    InternationalCalls                  => '',
    LongDistanceCalls                   => '',
    IncomingCalls                       => '',
    MobileCalls                         => '',
);