<?

 /*
 
   Параметры для web-интерфейса ATSlog
                                              
 */                                       
                                               
$sqlhost='localhost';
$sqldatabase='atslog_devel';
$sqlmaspasswd='123456789';
$sqlmasteruser='atslog_devel';
$sqltype='MySQL';
$model='KX-TA616RU';
$ADODB_CACHE_DIR = '/hosting/impersonate/collection';
$ADODB_CACHE_TTL = 60*60; // 1 час. Время жизни кеша SQL запросов.
$debugMode=TRUE; // Режим отладки.
$demoMode=FALSE; // Демонстрационный режим.

?>