<?php                   

// White wood color scheme

$COLORS = array (
    'SchemeName'			=> 'White wood',
    'BodyBgcolor'			=> 'bgcolor=#FFFFFF',
    'BodyText'				=> 'text=#000000',
    'BodyLink'				=> 'link=#0000CD',
    'BodyVlink'				=> 'vlink=#0000CD',
    'BodyAlink'				=> 'alink=#0000CD',
    'StyleBodyScrollbarBaseColor'	=> 'scrollbar-base-color:#F2F2F2;',
    'StyleBodyScrollbarArrowColor'	=> 'scrollbar-arrow-color:#8CC919;',
    'StyleAHover'			=> 'color:#1E90FF;',
    'StyleAMenu'			=> 'color:#E73030;',
    'StyleAMenuHover'			=> 'color:#CC3333;',
    'StyleInputBackground'		=> 'background:#FFFFFF;',
    'StyleSelectBackground'		=> 'background:#FFFFFF;',
    'StyleTextareaBackground'		=> 'background:#FFFFFF;',
    'StyleInputSubmitBackground'	=> 'background:#CECFCE',
    'StyleInputSubmitBorderRight'	=> 'BORDER-RIGHT:#B5B5B5 2px solid;',
    'StyleInputSubmitBorderTop'		=> 'BORDER-TOP:#FBFBFB 2px solid;',
    'StyleInputSubmitBorderLeft'	=> 'BORDER-LEFT:#FBFBFB 2px solid;',
    'StyleInputSubmitBorderBottom'	=> 'BORDER-BOTTOM:#A5A5A5 2px solid;',
    'FooterTableBgcolor'		=> 'bgcolor=#FFFFFF',
    'BaseTablesBgcolor'			=> 'bgcolor=#EFEBE7',
    'BaseTrBgcolor'			=> 'bgcolor=#EFEBE7',
    'BaseBorderTableBgcolor'		=> 'bgcolor=#8CC919',
    'TrOnmouseOne'			=> '#EFEBE7',
    'TrOnmouseTwo'			=> '#F6F6F6',
    'TrOnmouseThree'			=> '#FFFFE9',
    'AltogetherTrBgcolor'		=> 'bgcolor=#DDF8AD',
    'TotalTrBgcolor'			=> 'bgcolor=#F0E68C',
    'InternationalCalls'		=> 'color=#e400e4',
    'LongDistanceCalls'			=> 'color=green',
    'IncomingCalls'			=> 'color=#1A1AC1',
    'MobileCalls'			=> 'color=orange',
    'HiddenFont'			=> 'color=#D1D1D1',
);
