#!/bin/sh
# ATSlog version @version@ build @buildnumber@ www.atslog.dp.ua
# Copyright (C) 2003 Denis CyxoB www.yamiyam.dp.ua
#

for ac_prg in sed find [
do
    echo -n "checking if system file \"$ac_prg\" is existing: "
    for ac_dir in /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin
    do
        if [ -e "$ac_dir/$ac_prg" ]; then
            echo "YES"
	    FILE_NOT_EXISTS=0
	    break;
	else
	    FILE_NOT_EXISTS=1
        fi
    done
    if [ $FILE_NOT_EXISTS -ne 0 ]; then
        echo "NONE"
        echo "configure aborting!"
        exit 1
    fi
done

. ./version.inc
if [ -z $ver -o -z $build ];then
    echo Number of the version and the build not found!
    exit 1
else
    echo Prepare package for version $ver and build $build
    find ./ -type f -exec sed -i '' "s/@version@/$ver/g" {} \;                                              
    find ./ -type f -exec sed -i '' "s/@buildnumber@/$build/g" {} \;                                        
fi
