<?php                   

// Classic color scheme

$COLORS = array (
    'SchemeName'			=> 'Classic',
    'BodyBgcolor'			=> 'bgcolor=#FFFFFF',
    'BodyText'				=> 'text=#000000',
    'BodyLink'				=> 'link=#E73030',
    'BodyVlink'				=> 'vlink=#893700',
    'BodyAlink'				=> 'alink=#CC3333',
    'StyleBodyScrollbarBaseColor'	=> 'scrollbar-base-color:#F2F2F2;',
    'StyleBodyScrollbarArrowColor'	=> 'scrollbar-arrow-color:#E73030;',
    'StyleAHover'			=> 'color:#CC3333;',
    'StyleAMenu'			=> 'color:#E73030;',
    'StyleAMenuHover'			=> 'color:#CC3333;',
    'StyleInputBackground'		=> 'background :#F2F2F2;',
    'StyleSelectBackground'		=> 'background :#F2F2F2;',
    'StyleTextareaBackground'		=> 'background :#F2F2F2;',
    'StyleInputSubmitBackground'	=> 'background :#E3E3E3;',
    'StyleInputSubmitBorderRight'	=> 'BORDER-RIGHT: #B5B5B5 2px solid;',
    'StyleInputSubmitBorderTop'		=> 'BORDER-TOP: #FBFBFB 2px solid;',
    'StyleInputSubmitBorderLeft'	=> 'BORDER-LEFT: #FBFBFB 2px solid;',
    'StyleInputSubmitBorderBottom'	=> 'BORDER-BOTTOM: #B5B5B5 2px solid;',
    'FooterTableBgcolor'		=> 'bgcolor=#FFFFFF',
    'BaseTablesBgcolor'			=> 'bgcolor=#FFFFFF',
    'BaseTrBgcolor'			=> 'bgcolor=#FFFFFF',
    'BaseBorderTableBgcolor'		=> 'bgcolor=#F2F2F2',
    'TrOnmouseOne'			=> '#FFFFFF',
    'TrOnmouseTwo'			=> '#F6F6F6',
    'TrOnmouseThree'			=> '#FFFFE9',
    'AltogetherTrBgcolor'		=> 'bgcolor=#F0F0F0',
    'TotalTrBgcolor'			=> 'bgcolor=#E0E0E0',
    'InternationalCalls'		=> 'color=#e400e4',
    'LongDistanceCalls'			=> 'color=green',
    'IncomingCalls'			=> 'color=#1A1AC1',
    'MobileCalls'			=> 'color=orange',
    'HiddenFont'			=> 'color=#F2F2F2',
);
